services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8668:80"
    volumes:
      - ./nginx/nginx.conf/:/etc/nginx/conf.d/default.conf:re
      - ./src:/var/www/laravel
    depends_on:
      - db
      - app
    restart: always
    networks:
      - laravel

  app:
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./src:/var/www/laravel    
    container_name: laravel_app
    depends_on:
      - db
    networks:
      - laravel

  db:
    image: postgres:17
    ports:
      - "5432:5432"
    env_file:
      - env/db.env
    networks:
      - laravel

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: appsklimov@yandex.ru
      PGADMIN_DEFAULT_PASSWORD: leadadmin
    ports:
      - "5050:80" 
    depends_on:
      - db
    networks:
      - laravel

  composer:
    build:
      context: dockerfiles
      dockerfile: composer.Dockerfile
    volumes:
      - ./src:/var/www/laravel
    networks:
      - laravel

  artisan:
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile 
    volumes:
      - ./src:/var/www/laravel
    entrypoint: ["php", '/var/www/laravel/artisan']
    networks:
      - laravel
      
networks:
  laravel:    